# Python Numpy Array
NumPy array is a central data structure of the numpy library. The library’s name is short for “Numeric Python” or “Numerical Python”.
Reading and writing elements in a NumPy array is faster, and they support "vectorized" operations such as elementwise addition.

## Create a Array

In [1]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8]],int)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


## Inspect Your NumPy Arrays

In [2]:
# Print the number of `arr`'s dimensions
print("Dimension:",arr.ndim)

# Print the number of `arr`'s elements
print("No. of elements:",arr.size)

# Print the length of one array element in bytes
print("Length of one array",arr.itemsize)

# Print the length of `my_array`
print("length",len(arr))

# Change the data type of `my_array`
arr.astype(float)

Dimension: 2
No. of elements: 8
Length of one array 4
length 2


array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

## Arithmetic operations on array

In [3]:
x = np.array([[1,2,3,4], [5,6,7,8]],int)
y = np.array([[5,6,7,8], [1,2,3,4]],int)
print("Add `x` and `y`")
print(np.add(x,y))

print("Subtract `x` and `y`")
print(np.subtract(x,y))

print("Multiply `x` and `y`")
print(np.multiply(x,y))

print("Divide `x` and `y")
print(np.divide(x,y))

print("Calculate the remainder of `x` and `y`")
print(np.remainder(x,y))

Add `x` and `y`
[[ 6  8 10 12]
 [ 6  8 10 12]]
Subtract `x` and `y`
[[-4 -4 -4 -4]
 [ 4  4  4  4]]
Multiply `x` and `y`
[[ 5 12 21 32]
 [ 5 12 21 32]]
Divide `x` and `y
[[0.2        0.33333333 0.42857143 0.5       ]
 [5.         3.         2.33333333 2.        ]]
Calculate the remainder of `x` and `y`
[[1 2 3 4]
 [0 0 1 0]]


## Some functions of Numpy Array

In [4]:
print("Create an array of ones\n")
print(np.ones((3,4)))

print("\nCreate an array of zeros\n")
print(np.zeros((2,3,4),dtype=np.int16))

print("\nCreate an array with random values\n")
print(np.random.random((2,2)))

print("\nCreate an empty array\n")
print(np.empty((3,2)))

print("\nCreate a full array\n")
print(np.full((2,2),7))

print("\nCreate an array of evenly-spaced values\n")
print(np.arange(10,25,5))

print("\nCreate an array of evenly-spaced values using linspace\n")
print(np.linspace(0,2,9))

Create an array of ones

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Create an array of zeros

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]

Create an array with random values

[[0.32404168 0.42455725]
 [0.83420817 0.89580764]]

Create an empty array

[[0. 0.]
 [0. 0.]
 [0. 0.]]

Create a full array

[[7 7]
 [7 7]]

Create an array of evenly-spaced values

[10 15 20]

Create an array of evenly-spaced values using linspace

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


## Problem-


### 1.Divisible Sum Pairs

You are given an array of N integers ar=(ar[0],ar[1],...,ar[n-1]) and a positive integer K. Find and print the number of (i,j) pairs where i<j and ar[i]+ar[j] is divisible by K .

In [5]:
import numpy as np
n,k=map(int,input("Enter n and k:").split())
a=np.array([input("Enter numbers:").split() for _ in range(n)],int)
c,j=0,0
print("Pair are:")
for i in range(len(a)):
    j=1+i
    while j<n:
        if (a[i]+a[j])%k==0:
            print("a[",i,"] +","b[",j,"]=",a[i],"+",a[j],"=",a[i]+a[j])#just for ease understanding through output
            c=c+1
        j+=1
print("NO. of pairs:",c)

Enter n and k:6 3
Enter numbers:1
Enter numbers:2
Enter numbers:2
Enter numbers:6
Enter numbers:3
Enter numbers:4
Pair are:
a[ 0 ] + b[ 1 ]= [1] + [2] = [3]
a[ 0 ] + b[ 2 ]= [1] + [2] = [3]
a[ 1 ] + b[ 5 ]= [2] + [4] = [6]
a[ 2 ] + b[ 5 ]= [2] + [4] = [6]
a[ 3 ] + b[ 4 ]= [6] + [3] = [9]
NO. of pairs: 5


### 2. Convert a 1D array to a 2D array with 2 rows

In [6]:
arr = np.arange(10)
print("1D array:",arr)
print("2D array:\n",arr.reshape(2, -1))

1D array: [0 1 2 3 4 5 6 7 8 9]
2D array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


### 3. Reverse the rows of a 2D array array

In [7]:
arr = np.arange(9).reshape(3,3)
print(arr)
print("\nReverse\n")
print(arr[::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

Reverse

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### 4.Transpose a matrix 

In [9]:
matrix = np.array([[1,2,3],[4,5,6]]) 
print(matrix) 
print("\n") 
print(matrix.T)

[[1 2 3]
 [4 5 6]]


[[1 4]
 [2 5]
 [3 6]]
